apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment
  labels:
    app: komunikator
spec:
  replicas: 4
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
      - name: komunikator
        image: aleksanderfilek/wireappweb:1.0
        ports:
        - containerPort: 8080